feat: Add SARIF format generation for GHAS
appknox/appknox-github-action pull request #5
Opened 2024-05-22 11:04 UTC by ashujha301

1. SARIF input added.
2. Binary version updated to 1.4.6.
3. @zeit/ncc updated to @vercel/ncc.
4. Updated readme.

2024-05-23 06:34 UTC, ginilpg requested changes

2024-05-23 06:34 UTC, ginilpg commented on package.json
>      "@typescript-eslint/parser": "^4.8.0",
@ashujha301 Any reason to remove this?

2024-05-23 06:34 UTC, ginilpg commented on src/index.ts
> +    core.debug('APPKNOX-GITHUB-ACTION');
Remove debuggers

2024-05-23 06:34 UTC, ginilpg commented on src/constants.ts
> +export const binaryVersion = '1.4.6';
any consequences if we upgraded the version here?

2024-06-24 09:00 UTC, cosmosgenius requested changes

2024-06-24 09:00 UTC, cosmosgenius commented on src/appknox-inputs.ts
> +  sarif: string;
shouldn't this be boolean?

2024-06-24 09:00 UTC, cosmosgenius commented on src/constants.ts
> +  sarif = 'sarif',
```suggestion
  Sarif = 'sarif',
```

2024-06-24 09:00 UTC, cosmosgenius commented on src/index.ts
> +      core.setFailed('Unknown error occurred');
the msg should include the err object as well to know what error happened.

2024-06-24 09:00 UTC, cosmosgenius commented on src/input-helper.ts
> +  const sarifBool = core.getInput(Inputs.sarif, {required: true});
This is not a required field right?.

2024-06-26 08:26 UTC, cosmosgenius requested changes

2024-06-26 08:26 UTC, cosmosgenius commented on action.yml
> +    default: 'false'
```suggestion
    default: 'disabled'
```

2024-06-28 09:07 UTC, cosmosgenius approved these changes

2024-06-28 09:07 UTC, merged